name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_ HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: echo "SSH_KEY" > key-gen chmod 600 key-gen
          ssh -i key-gen -o StrictHostKeyChecking=no ${SERVER_USER}@${SERVER_HOST} '
          cd /home/ubuntu/app git pull origin nain sudo docker-compose down
          sudo docker-compose up --build -d'
